# Generated by Django 5.1 on 2024-08-14 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BU', 'Bicicleta Urbana'), ('BM', 'Bicicleta de Montaña'), ('BE', 'Bicicleta Eléctrica'), ('BT', 'Bicicleta de Turismo')], max_length=2)),
                ('marca', models.CharField(choices=[('GNT', 'Giant'), ('TRK', 'Trek'), ('SPZ', 'Specialized'), ('CND', 'Cannondale')], max_length=3)),
                ('descripcion', models.TextField()),
                ('picture', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('cantidad', models.IntegerField(default=1)),
                ('picture', models.ImageField(upload_to='product_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cantidad', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.producto')),
            ],
        ),
    ]
